//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.GameMenuSampleData
{
    using System;
    using System.ComponentModel;

    // To significantly reduce the sample data footprint in your production application, you can set
    // the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
    internal class GameMenuSampleData { }
#else

    public class GameMenuSampleData : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName)
        {
            if (this.PropertyChanged != null)
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        public GameMenuSampleData()
        {
            try
            {
                Uri resourceUri = new Uri("/ShooterGame;component/SampleData/GameMenuSampleData/GameMenuSampleData.xaml", UriKind.RelativeOrAbsolute);
                System.Windows.Application.LoadComponent(this, resourceUri);
            }
            catch
            {
            }
        }

        private Resolutions _Resolutions = new Resolutions();

        public Resolutions Resolutions
        {
            get
            {
                return this._Resolutions;
            }
        }

        private int _SelectedResolutionIndex = 0;

        public int SelectedResolutionIndex
        {
            get
            {
                return this._SelectedResolutionIndex;
            }
            set
            {
                if (this._SelectedResolutionIndex != value)
                {
                    this._SelectedResolutionIndex = value;
                    OnPropertyChanged("SelectedResolutionIndex");
                }
            }
        }

        private QualityPresets _QualityPresets = new QualityPresets();

        public QualityPresets QualityPresets
        {
            get
            {
                return this._QualityPresets;
            }
        }

        private int _SelectedQualityIndex = 0;

        public int SelectedQualityIndex
        {
            get
            {
                return this._SelectedQualityIndex;
            }
            set
            {
                if (this._SelectedQualityIndex != value)
                {
                    this._SelectedQualityIndex = value;
                    OnPropertyChanged("SelectedQualityIndex");
                }
            }
        }
    }

    public class ResolutionsItem : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName)
        {
            if (this.PropertyChanged != null)
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        public string _Value = string.Empty;

        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                if (this._Value != value)
                {
                    this._Value = value;
                    OnPropertyChanged("Value");
                }
            }
        }

        public override string ToString()
        {
            return Value;
        }
    }

    public class Resolutions : System.Collections.ObjectModel.ObservableCollection<ResolutionsItem>
    {
    }

    public class QualityPresetsItem : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName)
        {
            if (this.PropertyChanged != null)
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        public string _Value = string.Empty;

        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                if (this._Value != value)
                {
                    this._Value = value;
                    OnPropertyChanged("Value");
                }
            }
        }

        public override string ToString()
        {
            return Value;
        }
    }

    public class QualityPresets : System.Collections.ObjectModel.ObservableCollection<QualityPresetsItem>
    {
    }
#endif
}
